name: budget_app_starting
description: A  Flutter project to calculate the budget by Paulina and Sagnik


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.7
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  sign_button: ^2.0.2
  url_strategy: ^0.2.0
  url_launcher: 6.1.4
  flutter_svg: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

